// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 02/04/2026, 11:00:13
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/plugins/**/*.{js,ts,mjs}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/composables/**/*.{js,ts,mjs}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/utils/**/*.{js,ts,mjs}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Tiago/Área de Trabalho/Projetos/finances-nuxt/src/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;