// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].put').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.post').default>>>>
    }
    '/api/expenses/monthly/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/monthly/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/monthly/[id].put').default>>>>
    }
    '/api/expenses/monthly': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/monthly/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/monthly/index.post').default>>>>
    }
    '/api/expenses/occasional/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/occasional/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/occasional/[id].put').default>>>>
    }
    '/api/expenses/occasional': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/occasional/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses/occasional/index.post').default>>>>
    }
    '/api/incomes/monthly/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/monthly/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/monthly/[id].put').default>>>>
    }
    '/api/incomes/monthly': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/monthly/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/monthly/index.post').default>>>>
    }
    '/api/incomes/occasional/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/occasional/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/occasional/[id].put').default>>>>
    }
    '/api/incomes/occasional': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/occasional/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incomes/occasional/index.post').default>>>>
    }
    '/api/reports/by-category': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/by-category.get').default>>>>
    }
    '/api/reports/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/summary.get').default>>>>
    }
    '/api/wishlist/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/[id].put').default>>>>
    }
    '/api/wishlist': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}